require "#{__dir__}/model/Discount"
require "#{__dir__}/extention/FloatExtention"
require "#{__dir__}/model/PricedObject"
require "#{__dir__}/model/ShoppingBasket"
require "#{__dir__}/service/CashierEngine"
